### ISSUE TITLE
Request: New release

### ISSUE THREAD

**Issue by MadTooth** [bluemods/Bluecord#13] opened 2023-08-19 11:34 UTC
Can you make a new release of bluecord (preferably .apk versions with separated architectures/bitnesses)

**Comment by Mechite** [comment] 2023-08-21 02:21
Why would a new release be created if nothing has been edited yet? You do raise a good point with separating APKs by architecture - this would be something to improve on after we have automated patching, and then at some point hopefully CI/CD.

You can check for updates in the app via the Bluecord Mods menu.

**Comment by bluemods** [comment] 2023-08-27 16:13
Duplicate of #8 , seperate architectures is noted but unlikely as it would increase the complexity of future releases, as up to 6 apks would have to be made (1 for each architecture)

**Closed by bluemods** 2023-08-27 16:13 UTC
