### ISSUE TITLE
when will the new version be released

### ISSUE THREAD

**Issue by devcat86** [bluemods/Bluecord#14] opened 2023-08-21 18:07 UTC
I am a fan of bluecord, I consider it the only normal discord client, but there have been no updates for a long time. when the new one comes out, maybe there are some problems? There is a lot to add from the new version.. (translated from Russian via translator)

**Comment by JustKleo** [comment] 2023-08-27 00:40
Never this is malware

**Comment by bluemods** [comment] 2023-08-27 16:11
Duplicate of #8

**Closed by bluemods** 2023-08-27 16:11 UTC
